//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFHospital_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastaliklar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hastaliklar()
        {
            this.Doktorlars = new HashSet<Doktorlar>();
        }
    
        public int HastalikID { get; set; }
        public string Isim { get; set; }
        public Nullable<int> HastaID { get; set; }
    
        public virtual Hastalar Hastalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doktorlar> Doktorlars { get; set; }
    }
}
